#!/usr/local/sbin/charm-env python3

import os
from charmhelpers.core import hookenv
from charms import layer
from reactive import snap


layer.import_layer_libs()


try:
    # ensure /snap/bin is on the path
    snap.ensure_path()

    # ensure that reactive framework is setup for endpoints
    hookenv._run_atstart()

    stats = layer.aws.update_policies()

    hookenv.action_set(stats)
except layer.aws.AWSError as e:
    hookenv.action_fail(e.message)
